### ISSUE TITLE
Bot keeps crashing

### ISSUE THREAD

**Issue by AnakTeka** [WooAf/PoGoBoT#2]
Bot keeps crashing after runs for a while

```
Message: Exception of type 'PokemonGo.RocketAPI.Exceptions.InvalidResponseException' was thrown.
StackTrace:    at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__1`2.MoveNext() in C:\Users\WooAf\Desktop\PoGoBoT - Copy\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Client.<UpdatePlayerLocation>d__42.MoveNext() in C:\Users\WooAf\Desktop\PoGoBoT - Copy\PokemonGo.RocketAPI\Client.cs:line 399
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.GUI.MainForm.<ExecuteFarmingPokestopsAndPokemons>d__45.MoveNext() in C:\Users\WooAf\Desktop\PoGoBoT - Copy\PokemonGo.RocketAPI.GUI\MainForm.cs:line 785
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.GUI.MainForm.<startBottingSession>d__33.MoveNext() in C:\Users\WooAf\Desktop\PoGoBoT - Copy\PokemonGo.RocketAPI.GUI\MainForm.cs:line 429
```

I'm using PTC account.

**Comment by TAiS46** [comment]
Same for me

**Comment by WooAf** [comment]
I will fix that when PTC is coming back.

**Comment by poiuytrezaur** [comment]
Had some chain crashes after 20 min running, the bot kept crashing (no matter PTC or google account)

After stopping the bot right after said crash chain, i had a GUI crash when trying to start it again
[CrashLog.201607271816013841.txt](https://github.com/WooAf/PoGoBoT/files/386688/CrashLog.201607271816013841.txt)

**Comment by WooAf** [comment]
The crash should be fixed with 3.0.0, can you try please

**Comment by poiuytrezaur** [comment]
Now trying. I will keep the issue updated if any crash is found

**Comment by WooAf** [comment]
Thank you

**Comment by poiuytrezaur** [comment]
20 min run, no crash.
however, looks like the bot is clearing the table on evolving (the one saying Action : pokemon : CP)
IV is no longer on this table too !

**Comment by poiuytrezaur** [comment]
Just crashed at ~30 min
`An exception of type 'PokemonGo.RocketAPI.Exceptions.InvalidResponseException' occurred in mscorlib.dll but was not handled in user code`
On : 
```
        private async void btnStartFarming_Click(object sender, EventArgs e)
        {
            if (!await PreflightCheck())
```
Joining the logs
[CrashLog.201607271958042935.txt](https://github.com/WooAf/PoGoBoT/files/386770/CrashLog.201607271958042935.txt)
[CrashLog.201607271958095474.txt](https://github.com/WooAf/PoGoBoT/files/386772/CrashLog.201607271958095474.txt)
[CrashLog.201607271958148113.txt](https://github.com/WooAf/PoGoBoT/files/386774/CrashLog.201607271958148113.txt)
[CrashLog.201607271958200588.txt](https://github.com/WooAf/PoGoBoT/files/386769/CrashLog.201607271958200588.txt)
[CrashLog.201607271958253103.txt](https://github.com/WooAf/PoGoBoT/files/386771/CrashLog.201607271958253103.txt)
[CrashLog.201607271958305526.txt](https://github.com/WooAf/PoGoBoT/files/386773/CrashLog.201607271958305526.txt)
[CrashLog.201607271958358075.txt](https://github.com/WooAf/PoGoBoT/files/386775/CrashLog.201607271958358075.txt)
[CrashLog.201607271958410586.txt](https://github.com/WooAf/PoGoBoT/files/386777/CrashLog.201607271958410586.txt)
[CrashLog.201607271958463082.txt](https://github.com/WooAf/PoGoBoT/files/386778/CrashLog.201607271958463082.txt)
[CrashLog.201607271958515431.txt](https://github.com/WooAf/PoGoBoT/files/386780/CrashLog.201607271958515431.txt)
[CrashLog.201607271958568046.txt](https://github.com/WooAf/PoGoBoT/files/386776/CrashLog.201607271958568046.txt)
[CrashLog.201607271959020526.txt](https://github.com/WooAf/PoGoBoT/files/386779/CrashLog.201607271959020526.txt)
[CrashLog.201607271959073593.txt](https://github.com/WooAf/PoGoBoT/files/386781/CrashLog.201607271959073593.txt)
[CrashLog.201607271959126317.txt](https://github.com/WooAf/PoGoBoT/files/386782/CrashLog.201607271959126317.txt)
[CrashLog.201607271957117310.txt](https://github.com/WooAf/PoGoBoT/files/386783/CrashLog.201607271957117310.txt)
[CrashLog.201607271957169954.txt](https://github.com/WooAf/PoGoBoT/files/386786/CrashLog.201607271957169954.txt)
[CrashLog.201607271957222400.txt](https://github.com/WooAf/PoGoBoT/files/386784/CrashLog.201607271957222400.txt)
[CrashLog.201607271957275135.txt](https://github.com/WooAf/PoGoBoT/files/386785/CrashLog.201607271957275135.txt)
[CrashLog.201607271957327633.txt](https://github.com/WooAf/PoGoBoT/files/386788/CrashLog.201607271957327633.txt)
[CrashLog.201607271957380448.txt](https://github.com/WooAf/PoGoBoT/files/386787/CrashLog.201607271957380448.txt)
[CrashLog.201607271957432812.txt](https://github.com/WooAf/PoGoBoT/files/386790/CrashLog.201607271957432812.txt)
[CrashLog.201607271957485389.txt](https://github.com/WooAf/PoGoBoT/files/386789/CrashLog.201607271957485389.txt)
[CrashLog.201607271957537836.txt](https://github.com/WooAf/PoGoBoT/files/386792/CrashLog.201607271957537836.txt)
[CrashLog.201607271957590440.txt](https://github.com/WooAf/PoGoBoT/files/386791/CrashLog.201607271957590440.txt)

**Comment by WooAf** [comment]
Thank you, checking

**Comment by poiuytrezaur** [comment]
EDIT : NVM IV are on the table

**Comment by WooAf** [comment]
I have started the bot on my computer and I debug it

**Comment by poiuytrezaur** [comment]
The IV column is disapearing somehow (I haven't noticed when tho)

**Comment by WooAf** [comment]
What do you mean the IV column is disapearing ? can you give me more information please

**Comment by poiuytrezaur** [comment]
![untitled](https://cloud.githubusercontent.com/assets/3758280/17188913/793cc2ca-543f-11e6-9e23-3d0b6737459e.png)
This column is hidden after a certain time. pretty sure it is after a transferring or evolving session

**Comment by TAiS46** [comment]
`Message: Eine Ausnahme vom Typ "PokemonGo.RocketAPI.Exceptions.InvalidResponseException" wurde ausgelöst.
StackTrace:    bei PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__1`2.MoveNext() in C:\Users\WooAf\Desktop\PoGoBoT - Copy\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:Zeile 39.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   bei PokemonGo.RocketAPI.Client.<GetMapObjects>d__32.MoveNext() in C:\Users\WooAf\Desktop\PoGoBoT - Copy\PokemonGo.RocketAPI\Client.cs:Zeile 254.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   bei PokemonGo.RocketAPI.GUI.MainForm.<ExecuteFarmingPokestopsAndPokemons>d__45.MoveNext() in C:\Users\WooAf\Desktop\PoGoBoT - Copy\PokemonGo.RocketAPI.GUI\MainForm.cs:Zeile 783.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   bei PokemonGo.RocketAPI.GUI.MainForm.<StartBottingSession>d__33.MoveNext() in C:\Users\WooAf\Desktop\PoGoBoT - Copy\PokemonGo.RocketAPI.GUI\MainForm.cs:Zeile 429.
`

Did you see that this is your path?

**Comment by WooAf** [comment]
Should be fixed, running for almost 45 mins on my VPS
