### ISSUE TITLE
Unable to farm again after you stop farming

### ISSUE THREAD

**Issue by JordyGitHub** [WooAf/PoGoBoT#20]
if you stop farming and then start farming, I'm receiving the following error: 

[22:22:47 PM] Unhandled exception: System.InvalidOperationException: Cross-thread operation not valid: Control 'dGrid' accessed from a thread other than the thread it was created on.
   at System.Windows.Forms.Control.get_Handle()
   at System.Windows.Forms.DataGridView.FlushDisplayedChanged()
   at System.Windows.Forms.DataGridView.PerformLayoutPrivate(Boolean useRowShortcut, Boolean computeVisibleRows, Boolean invalidInAdjustFillingColumns, Boolean repositionEditingControl)
   at System.Windows.Forms.DataGridView.ResetUIState(Boolean useRowShortcut, Boolean computeVisibleRows)
   at System.Windows.Forms.DataGridViewRowCollection.OnCollectionChanged_PreNotification(CollectionChangeAction cca, Int32 rowIndex, Int32 rowCount, DataGridViewRow& dataGridViewRow, Boolean changeIsInsertion)
   at System.Windows.Forms.DataGridViewRowCollection.OnCollectionChanged(CollectionChangeEventArgs e, Int32 rowIndex, Int32 rowCount, Boolean changeIsDeletion, Boolean changeIsInsertion, Boolean recreateNewRow, Point newCurrentCell)
   at System.Windows.Forms.DataGridViewRowCollection.ClearInternal(Boolean recreateNewRow)
   at System.Windows.Forms.DataGridViewRowCollection.Clear()
   at PokemonGo.RocketAPI.Window.MainForm.<btnStartFarming_Click>b__45_0() in E:\Workspace\GO-Bot-master\JordyGitHub\PoGoBoT\PokemonGo\RocketAPI\Window\MainForm.cs:line 1036

Reproduction scenario:
Start farming
wait till it actually farms
Stop farming
wait till it stopped farming
Start farming
above error is shown, no farming

**Comment by WooAf** [comment]
Fixed on 4.0.2

**Comment by JordyGitHub** [comment]
Yes, verified and it's all good now :) Thanks
